// <auto-generated />
using System;
using CinemaProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaProject.Migrations
{
    [DbContext(typeof(RapChieuPhimContext))]
    [Migration("20250704213920_AddDanhGiaPhim")]
    partial class AddDanhGiaPhim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaProject.Models.ApDungKhuyenMaiDoAn", b =>
                {
                    b.Property<string>("IdApDungDoAn")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idApDungDoAn");

                    b.Property<string>("IdDonHang")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idDonHang");

                    b.Property<string>("IdKhuyenMai")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idKhuyenMai");

                    b.Property<int>("SoTienGiam")
                        .HasColumnType("int");

                    b.HasKey("IdApDungDoAn")
                        .HasName("PK__ApDungKh__CAA676886177205B");

                    b.HasIndex("IdDonHang");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("ApDungKhuyenMaiDoAn", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.ApDungKhuyenMaiVe", b =>
                {
                    b.Property<string>("IdApDung")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idApDung");

                    b.Property<string>("IdDatVe")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idDatVe");

                    b.Property<string>("IdKhuyenMai")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idKhuyenMai");

                    b.Property<int>("SoTienGiam")
                        .HasColumnType("int");

                    b.HasKey("IdApDung")
                        .HasName("PK__ApDungKh__D551A5270F626334");

                    b.HasIndex("IdDatVe");

                    b.HasIndex("IdKhuyenMai");

                    b.ToTable("ApDungKhuyenMaiVe", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.BookVe", b =>
                {
                    b.Property<string>("IdBookVe")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idBookVe");

                    b.Property<string>("GheNgoi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdKhach")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idKhach");

                    b.Property<string>("IdLich")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idLich");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("date");

                    b.Property<int?>("TongTien")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdBookVe")
                        .HasName("PK__BookVe__...");

                    b.HasIndex("IdKhach");

                    b.HasIndex("IdLich");

                    b.ToTable("BookVe", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.ComboMonAn", b =>
                {
                    b.Property<string>("IdMonAn")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idMonAn");

                    b.Property<string>("CacMonAn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("GiaTien")
                        .HasColumnType("int");

                    b.HasKey("IdMonAn")
                        .HasName("PK__ComboMon__164239B628BA4B42");

                    b.ToTable("ComboMonAn", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.DanhGiaPhim", b =>
                {
                    b.Property<string>("IdDanhGia")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idDanhGia");

                    b.Property<string>("BinhLuan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("binhLuan");

                    b.Property<string>("IdKhach")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idKhach");

                    b.Property<string>("IdPhim")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idPhim");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("date")
                        .HasColumnName("ngayDanhGia");

                    b.Property<int>("SoSao")
                        .HasColumnType("int")
                        .HasColumnName("soSao");

                    b.HasKey("IdDanhGia");

                    b.HasIndex("IdKhach");

                    b.HasIndex("IdPhim");

                    b.ToTable("DanhGiaPhim", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.DatVe", b =>
                {
                    b.Property<string>("IdDatVe")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idDatVe");

                    b.Property<string>("GheNgoi")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IdKhach")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idKhach");

                    b.Property<string>("IdLich")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idLich");

                    b.Property<DateTime?>("ThoiGianDat")
                        .HasColumnType("date");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("IdDatVe")
                        .HasName("PK__DatVe__B08CC224E1DC4A17");

                    b.HasIndex("IdKhach");

                    b.HasIndex("IdLich");

                    b.ToTable("DatVe", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.DoiTacPhim", b =>
                {
                    b.Property<string>("IdDoiTac")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idDoiTac");

                    b.Property<string>("DiaChidt")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmailDoiTac")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SoDienThoaiDt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SoDienThoaiDT");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdDoiTac")
                        .HasName("PK__DoiTacPh__AF8143C63278ABF2");

                    b.HasIndex(new[] { "EmailDoiTac" }, "UQ__DoiTacPh__82F98F8782557AAD")
                        .IsUnique();

                    b.ToTable("DoiTacPhim", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.DonHangDoAn", b =>
                {
                    b.Property<string>("IdDonHang")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idDonHang");

                    b.Property<string>("DanhSachMon")
                        .HasColumnType("text");

                    b.Property<string>("IdKhach")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idKhach");

                    b.Property<DateTime?>("ThoiGianDat")
                        .HasColumnType("date");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("IdDonHang")
                        .HasName("PK__DonHangD__D5DE7ED7B35708B6");

                    b.HasIndex("IdKhach");

                    b.ToTable("DonHangDoAn", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.KhachHang", b =>
                {
                    b.Property<string>("IdKhach")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idKhach");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatKhauKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdKhach")
                        .HasName("PK__KhachHan__385411B93250E4B1");

                    b.HasIndex(new[] { "Email" }, "UQ__KhachHan__A9D10534DE7EC02D")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.KhuyenMai", b =>
                {
                    b.Property<string>("IdKhuyenMai")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idKhuyenMai");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<int?>("PhanTramGiam")
                        .HasColumnType("int");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdKhuyenMai")
                        .HasName("PK__KhuyenMa__637EEC7CBC51F554");

                    b.HasIndex(new[] { "TenKhuyenMai" }, "UQ__KhuyenMa__A956B87C9A9E0698")
                        .IsUnique();

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.LichChieu", b =>
                {
                    b.Property<string>("IdLich")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idLich");

                    b.Property<int>("GiaVe")
                        .HasColumnType("int");

                    b.Property<string>("GioChieu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("IdPhim")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idPhim");

                    b.Property<string>("IdPhong")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idPhong");

                    b.Property<DateTime>("NgayChieu")
                        .HasColumnType("date");

                    b.HasKey("IdLich")
                        .HasName("PK__LichChie__1439F14FF8768ABF");

                    b.HasIndex("IdPhim");

                    b.HasIndex("IdPhong");

                    b.ToTable("LichChieu", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.NhanVien", b =>
                {
                    b.Property<string>("IdNhanVien")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idNhanVien");

                    b.Property<string>("IdRap")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idRap");

                    b.Property<int?>("Luong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ViTri")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNhanVien")
                        .HasName("PK__NhanVien__214E8258A2EC7880");

                    b.HasIndex("IdRap");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.Phim", b =>
                {
                    b.Property<string>("IdPhim")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idPhim");

                    b.Property<string>("DoTuoiPhuHop")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("IdTheLoai")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idTheLoai");

                    b.Property<DateTime?>("NgayKhoiChieu")
                        .HasColumnType("date");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("IdPhim")
                        .HasName("PK__Phim__BFC6F683A1A705DC");

                    b.HasIndex("IdTheLoai");

                    b.ToTable("Phim", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.PhimDoiTac", b =>
                {
                    b.Property<string>("IdPhim")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idPhim");

                    b.Property<string>("IdDoiTac")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idDoiTac");

                    b.Property<DateTime>("NgayKiHopDong")
                        .HasColumnType("date");

                    b.HasKey("IdPhim", "IdDoiTac")
                        .HasName("PK__PhimDoiT__C53EE2BF07F62161");

                    b.HasIndex("IdDoiTac");

                    b.ToTable("PhimDoiTac", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.PhongChieu", b =>
                {
                    b.Property<string>("IdPhong")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idPhong");

                    b.Property<string>("IdRap")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idRap");

                    b.Property<int>("SoLuongGhe")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPhong")
                        .HasName("PK__PhongChi__E540EED4A143A496");

                    b.HasIndex("IdRap");

                    b.ToTable("PhongChieu", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.Rap", b =>
                {
                    b.Property<string>("IdRap")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idRap");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenRap")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdRap")
                        .HasName("PK__Rap__3C87B153392A9CEB");

                    b.ToTable("Rap", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.TaiKhoanNhanVien", b =>
                {
                    b.Property<string>("IdTaiKhoan")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idTaiKhoan");

                    b.Property<string>("IdNhanVien")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idNhanVien");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTaiKhoan")
                        .HasName("PK__TaiKhoan__8FA29E4A67B83B4A");

                    b.HasIndex("IdNhanVien");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ__TaiKhoan__55F68FC0E94E4D30")
                        .IsUnique();

                    b.ToTable("TaiKhoanNhanVien", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.TheLoai", b =>
                {
                    b.Property<string>("IdTheLoai")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idTheLoai");

                    b.Property<string>("TenTheLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTheLoai")
                        .HasName("PK__TheLoai__890D7EC8F0F7909F");

                    b.ToTable("TheLoai", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.VeXemPhim", b =>
                {
                    b.Property<string>("IdVe")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idVe");

                    b.Property<string>("Ghe")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("IdDatVe")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("idDatVe");

                    b.HasKey("IdVe")
                        .HasName("PK__VeXemPhi__9DB83851A88F47BF");

                    b.HasIndex("IdDatVe");

                    b.ToTable("VeXemPhim", (string)null);
                });

            modelBuilder.Entity("CinemaProject.Models.ApDungKhuyenMaiDoAn", b =>
                {
                    b.HasOne("CinemaProject.Models.DonHangDoAn", "IdDonHangNavigation")
                        .WithMany("ApDungKhuyenMaiDoAns")
                        .HasForeignKey("IdDonHang")
                        .HasConstraintName("FK__ApDungKhu__idDon__5BE2A6F2");

                    b.HasOne("CinemaProject.Models.KhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("ApDungKhuyenMaiDoAns")
                        .HasForeignKey("IdKhuyenMai")
                        .HasConstraintName("FK__ApDungKhu__idKhu__5CD6CB2B");

                    b.Navigation("IdDonHangNavigation");

                    b.Navigation("IdKhuyenMaiNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.ApDungKhuyenMaiVe", b =>
                {
                    b.HasOne("CinemaProject.Models.DatVe", "IdDatVeNavigation")
                        .WithMany("ApDungKhuyenMaiVes")
                        .HasForeignKey("IdDatVe")
                        .HasConstraintName("FK__ApDungKhu__idDat__5812160E");

                    b.HasOne("CinemaProject.Models.KhuyenMai", "IdKhuyenMaiNavigation")
                        .WithMany("ApDungKhuyenMaiVes")
                        .HasForeignKey("IdKhuyenMai")
                        .HasConstraintName("FK__ApDungKhu__idKhu__59063A47");

                    b.Navigation("IdDatVeNavigation");

                    b.Navigation("IdKhuyenMaiNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.BookVe", b =>
                {
                    b.HasOne("CinemaProject.Models.KhachHang", "IdKhachNavigation")
                        .WithMany("BookVes")
                        .HasForeignKey("IdKhach")
                        .HasConstraintName("FK_BookVe_KhachHang");

                    b.HasOne("CinemaProject.Models.LichChieu", "IdLichNavigation")
                        .WithMany("BookVes")
                        .HasForeignKey("IdLich")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookVe_LichChieu");

                    b.Navigation("IdKhachNavigation");

                    b.Navigation("IdLichNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.DanhGiaPhim", b =>
                {
                    b.HasOne("CinemaProject.Models.KhachHang", "KhachHang")
                        .WithMany("DanhGiaPhims")
                        .HasForeignKey("IdKhach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DanhGiaPhim_KhachHang");

                    b.HasOne("CinemaProject.Models.Phim", "Phim")
                        .WithMany("DanhGiaPhims")
                        .HasForeignKey("IdPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DanhGiaPhim_Phim");

                    b.Navigation("KhachHang");

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("CinemaProject.Models.DatVe", b =>
                {
                    b.HasOne("CinemaProject.Models.KhachHang", "IdKhachNavigation")
                        .WithMany("DatVes")
                        .HasForeignKey("IdKhach")
                        .HasConstraintName("FK__DatVe__idKhach__47DBAE45");

                    b.HasOne("CinemaProject.Models.LichChieu", "IdLichNavigation")
                        .WithMany("DatVes")
                        .HasForeignKey("IdLich")
                        .HasConstraintName("FK__DatVe__idLich__48CFD27E");

                    b.Navigation("IdKhachNavigation");

                    b.Navigation("IdLichNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.DonHangDoAn", b =>
                {
                    b.HasOne("CinemaProject.Models.KhachHang", "IdKhachNavigation")
                        .WithMany("DonHangDoAns")
                        .HasForeignKey("IdKhach")
                        .HasConstraintName("FK__DonHangDo__idKha__5165187F");

                    b.Navigation("IdKhachNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.LichChieu", b =>
                {
                    b.HasOne("CinemaProject.Models.Phim", "IdPhimNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("IdPhim")
                        .HasConstraintName("FK__LichChieu__idPhi__412EB0B6");

                    b.HasOne("CinemaProject.Models.PhongChieu", "IdPhongNavigation")
                        .WithMany("LichChieus")
                        .HasForeignKey("IdPhong")
                        .HasConstraintName("FK__LichChieu__idPho__4222D4EF");

                    b.Navigation("IdPhimNavigation");

                    b.Navigation("IdPhongNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.NhanVien", b =>
                {
                    b.HasOne("CinemaProject.Models.Rap", "IdRapNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdRap")
                        .HasConstraintName("FK__NhanVien__idRap__4E88ABD4");

                    b.Navigation("IdRapNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.Phim", b =>
                {
                    b.HasOne("CinemaProject.Models.TheLoai", "IdTheLoaiNavigation")
                        .WithMany("Phims")
                        .HasForeignKey("IdTheLoai")
                        .HasConstraintName("FK__Phim__idTheLoai__3E52440B");

                    b.Navigation("IdTheLoaiNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.PhimDoiTac", b =>
                {
                    b.HasOne("CinemaProject.Models.DoiTacPhim", "IdDoiTacNavigation")
                        .WithMany("PhimDoiTacs")
                        .HasForeignKey("IdDoiTac")
                        .IsRequired()
                        .HasConstraintName("FK__PhimDoiTa__idDoi__6754599E");

                    b.HasOne("CinemaProject.Models.Phim", "IdPhimNavigation")
                        .WithMany("PhimDoiTacs")
                        .HasForeignKey("IdPhim")
                        .IsRequired()
                        .HasConstraintName("FK__PhimDoiTa__idPhi__66603565");

                    b.Navigation("IdDoiTacNavigation");

                    b.Navigation("IdPhimNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.PhongChieu", b =>
                {
                    b.HasOne("CinemaProject.Models.Rap", "IdRapNavigation")
                        .WithMany("PhongChieus")
                        .HasForeignKey("IdRap")
                        .HasConstraintName("FK__PhongChie__idRap__398D8EEE");

                    b.Navigation("IdRapNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.TaiKhoanNhanVien", b =>
                {
                    b.HasOne("CinemaProject.Models.NhanVien", "IdNhanVienNavigation")
                        .WithMany("TaiKhoanNhanViens")
                        .HasForeignKey("IdNhanVien")
                        .HasConstraintName("FK__TaiKhoanN__idNha__60A75C0F");

                    b.Navigation("IdNhanVienNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.VeXemPhim", b =>
                {
                    b.HasOne("CinemaProject.Models.DatVe", "IdDatVeNavigation")
                        .WithMany("VeXemPhims")
                        .HasForeignKey("IdDatVe")
                        .HasConstraintName("FK__VeXemPhim__idDat__4BAC3F29");

                    b.Navigation("IdDatVeNavigation");
                });

            modelBuilder.Entity("CinemaProject.Models.DatVe", b =>
                {
                    b.Navigation("ApDungKhuyenMaiVes");

                    b.Navigation("VeXemPhims");
                });

            modelBuilder.Entity("CinemaProject.Models.DoiTacPhim", b =>
                {
                    b.Navigation("PhimDoiTacs");
                });

            modelBuilder.Entity("CinemaProject.Models.DonHangDoAn", b =>
                {
                    b.Navigation("ApDungKhuyenMaiDoAns");
                });

            modelBuilder.Entity("CinemaProject.Models.KhachHang", b =>
                {
                    b.Navigation("BookVes");

                    b.Navigation("DanhGiaPhims");

                    b.Navigation("DatVes");

                    b.Navigation("DonHangDoAns");
                });

            modelBuilder.Entity("CinemaProject.Models.KhuyenMai", b =>
                {
                    b.Navigation("ApDungKhuyenMaiDoAns");

                    b.Navigation("ApDungKhuyenMaiVes");
                });

            modelBuilder.Entity("CinemaProject.Models.LichChieu", b =>
                {
                    b.Navigation("BookVes");

                    b.Navigation("DatVes");
                });

            modelBuilder.Entity("CinemaProject.Models.NhanVien", b =>
                {
                    b.Navigation("TaiKhoanNhanViens");
                });

            modelBuilder.Entity("CinemaProject.Models.Phim", b =>
                {
                    b.Navigation("DanhGiaPhims");

                    b.Navigation("LichChieus");

                    b.Navigation("PhimDoiTacs");
                });

            modelBuilder.Entity("CinemaProject.Models.PhongChieu", b =>
                {
                    b.Navigation("LichChieus");
                });

            modelBuilder.Entity("CinemaProject.Models.Rap", b =>
                {
                    b.Navigation("NhanViens");

                    b.Navigation("PhongChieus");
                });

            modelBuilder.Entity("CinemaProject.Models.TheLoai", b =>
                {
                    b.Navigation("Phims");
                });
#pragma warning restore 612, 618
        }
    }
}
